extern signed char var_2;
extern unsigned char var_3;
extern unsigned char var_4;
extern signed char var_8;
extern unsigned char var_9;
extern unsigned char var_16;
extern int zero;
extern unsigned int var_18;
extern unsigned int var_19;
extern unsigned char var_20;
extern unsigned char var_21;
