extern unsigned long long int var_4;
extern unsigned long long int var_5;
extern int var_8;
extern unsigned long long int var_9;
extern unsigned long long int var_11;
extern int var_16;
extern int var_19;
extern int zero;
extern int var_20;
extern unsigned long long int var_21;
extern unsigned int var_22;
extern int var_23;
extern int var_24;
extern unsigned int arr_0 [22] [22] ;
extern int arr_1 [22] ;
extern unsigned int arr_3 [22] [22] [22] ;
extern unsigned int arr_4 [22] [22] [22] ;
extern int arr_5 [22] [22] [22] ;
extern int arr_6 [22] [22] [22] ;
