extern signed char var_0;
extern signed char var_1;
extern unsigned int var_2;
extern signed char var_4;
extern long long int var_5;
extern unsigned int var_9;
extern _Bool var_10;
extern int zero;
extern unsigned char var_11;
extern unsigned short var_12;
extern _Bool var_13;
extern unsigned int var_14;
extern unsigned char var_15;
extern unsigned short var_16;
