extern unsigned int var_1;
extern int var_2;
extern short var_3;
extern int var_5;
extern short var_6;
extern unsigned int var_7;
extern unsigned long long int var_8;
extern short var_10;
extern int zero;
extern unsigned long long int var_12;
extern int var_13;
extern unsigned int var_14;
extern signed char var_15;
extern int arr_1 [21] ;
