extern unsigned char var_6;
extern signed char var_7;
extern int var_16;
extern int zero;
extern signed char var_18;
extern int var_19;
extern long long int var_20;
extern long long int var_21;
extern unsigned int var_22;
extern int var_23;
extern int var_24;
extern unsigned char var_25;
extern unsigned int var_26;
extern _Bool var_27;
extern signed char arr_0 [25] ;
extern short arr_1 [25] ;
extern unsigned int arr_2 [25] [25] ;
extern unsigned short arr_5 [15] ;
extern unsigned int arr_6 [15] ;
extern signed char arr_12 [24] ;
extern long long int arr_3 [25] ;
extern unsigned short arr_4 [25] ;
extern unsigned int arr_13 [24] ;
