extern short var_0;
extern _Bool var_1;
extern unsigned char var_4;
extern int var_6;
extern unsigned long long int var_13;
extern int zero;
extern unsigned short var_16;
extern _Bool var_17;
extern long long int var_18;
extern unsigned char var_19;
extern int var_20;
extern unsigned char var_21;
extern unsigned char arr_1 [15] ;
extern unsigned char arr_7 [15] [15] [15] ;
extern unsigned short arr_11 [15] [15] [15] ;
