extern short var_0;
extern short var_2;
extern unsigned char var_4;
extern short var_6;
extern unsigned char var_7;
extern unsigned char var_8;
extern unsigned char var_9;
extern short var_10;
extern short var_12;
extern short var_13;
extern short var_15;
extern short var_16;
extern short var_17;
extern int zero;
extern short var_18;
extern short var_19;
extern unsigned char var_20;
extern unsigned char var_21;
extern short var_22;
