extern short var_2;
extern _Bool var_3;
extern signed char var_4;
extern short var_6;
extern signed char var_9;
extern unsigned char var_10;
extern _Bool var_11;
extern unsigned short var_12;
extern unsigned long long int var_15;
extern signed char var_16;
extern unsigned long long int var_17;
extern int zero;
extern long long int var_19;
extern long long int var_20;
extern _Bool var_21;
extern short var_22;
extern long long int var_23;
extern long long int var_24;
extern _Bool var_25;
extern short var_26;
extern _Bool var_27;
extern _Bool arr_0 [23] ;
extern short arr_1 [23] [23] ;
extern unsigned long long int arr_3 [23] [23] ;
extern unsigned long long int arr_4 [23] ;
extern _Bool arr_5 [23] [23] [23] ;
extern signed char arr_6 [23] [23] [23] ;
extern signed char arr_7 [23] [23] [23] ;
extern short arr_8 [23] [23] ;
extern unsigned char arr_9 [23] ;
extern unsigned int arr_11 [23] [23] ;
extern long long int arr_10 [23] [23] [23] ;
extern unsigned long long int arr_13 [23] ;
extern unsigned short arr_14 [23] ;
