extern long long int var_1;
extern long long int var_3;
extern int var_5;
extern short var_8;
extern short var_11;
extern unsigned char var_17;
extern int zero;
extern unsigned char var_18;
extern _Bool var_19;
extern unsigned char var_20;
extern short var_21;
